DOCUMENT_NUMBER:"DOCUMENT_NUMBER",

COMPANY_PROFILE:"COMPANY_PROFILE",

SYSTEM_CONFIGURATION:"SYSTEM_CONFIGURATION",

WAREHOUSE:"WAREHOUSE",

RACK:"RACK",

SHIFT:"SHIFT",

JOB_PRIORITY:"JOB_PRIORITY",

VEHICLE_MODEL:"VEHICLE_MODEL",

TRANSMISSION:"TRANSMISSION",

FUEL_TYPE:"FUEL_TYPE"