export const ROLE={
OWNER:"OWNER",
ADMIN:"ADMIN",
SA:"SERVICE_ADVISOR",
MECHANIC:"MECHANIC",
CASHIER:"CASHIER"
};

export const WO_STATUS={
OPEN:"OPEN",
PROCESS:"PROCESS",
FINISH:"FINISH",
DELIVERED:"DELIVERED"
};
